(* Generated by ocaml-rs *)

open! Bigarray

(* file: mod.rs *)

type layer
type retry_layer
external new_retry_layer: int option -> float option -> bool -> float option -> float option -> retry_layer  = "new_retry_layer"
