(* Generated by ocaml-rs *)

open! Bigarray

(* file: mod.rs *)

type blocking_operator
external constructor: Scheme.scheme -> (string * string) list -> (blocking_operator, string) Result.t  = "constructor"
external is_exist: blocking_operator -> string -> (bool, string) Result.t  = "is_exist"
external create_dir: blocking_operator -> string -> (bool, string) Result.t  = "create_dir"
external read: blocking_operator -> string -> (char array, string) Result.t  = "read"
external write: blocking_operator -> string -> bytes -> (unit, string) Result.t  = "write"
external copy: blocking_operator -> string -> string -> (unit, string) Result.t  = "copy"
external rename: blocking_operator -> string -> string -> (unit, string) Result.t  = "rename"
external delete: blocking_operator -> string -> (unit, string) Result.t  = "delete"
external remove: blocking_operator -> string array -> (unit, string) Result.t  = "remove"
external remove_all: blocking_operator -> string -> (unit, string) Result.t  = "remove_all"
